- name: docker | {{ docker_version }} | Setup on CentOS 7
  tags: &tags
    - always
  include_tasks: os.centos-7.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
- name: docker | {{ docker_version }} | Setup on CentOS 8
  tags: *tags
  include_tasks: os.centos-8.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'
- name: docker | Setup on Debian
  tags: *tags
  include_tasks: os.debian.yml
  when: ansible_distribution == 'Debian'
- name: docker | Setup on Ubuntu
  tags: *tags
  include_tasks: os.ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
- name: docker | {{ docker_version }} | Setup on Alpine 3.x
  tags: *tags
  include_tasks: os.alpine-3.yml
  when: ansible_distribution == 'Alpine' and ansible_distribution_major_version == '3'
