- name: docker | Install requirements
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - python3-pip
  tags: &TAGS
    - docker

- name: docker | Add GPG key
  apt_key:
    id: 0EBFCD88
    url: "https://download.docker.com/linux/{{ ansible_os_family | lower }}/gpg"
    state: present
  tags: *TAGS

- name: docker | Add latest stable repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
  tags: *TAGS

- name: docker | Install app
  apt:
    name: docker-ce
  tags: *TAGS

- name: docker | Install SDK
  tags: *TAGS
  pip:
    name: docker
  when: docker_sdk