- name: docker | {{ docker_version }} | plugins | setup
  tags:
    - always
  community.docker.docker_plugin:
    plugin_name: "{{ item.name }}"
    alias: "{{ item.alias | default(item.name) }}"
    state: "{{ 'present' if item.install | default(True) else 'absent' }}"
  loop: "{{ docker_plugins }}"
  loop_control:
    label: "
      {{ item.name }} - {{ item.alias | default(item.name) }} (
        install={{ 'true' if item.install | default(True) else 'false' }};
        enable={{ 'true' if item.enable | default(True) else 'false' }}
      )"
  when: docker_plugins | default(None)

- name: docker | {{ docker_version }} | plugins | enable
  tags:
    - always
  community.docker.docker_plugin:
    plugin_name: "{{ item.name }}"
    alias: "{{ item.alias | default(item.name) }}"
    state: "{{ 'enable' if item.enable | default(True) else 'disable' }}"
  loop: "{{ docker_plugins }}"
  loop_control:
    label: "
      {{ item.name }} - {{ item.alias | default(item.name) }} (
        install={{ 'true' if item.install | default(True) else 'false' }};
        enable={{ 'true' if item.enable | default(True) else 'false' }}
      )"
  when: docker_plugins | default(None)
